spring:
  application:
    name: oauth2
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fairflow
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/api
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:9090/realms/safari

keycloak:
  url: http://localhost:9090
  client:
    id: fairflow
    secret: mM0E07pZOxCKkYICMWfIhGp74vs0Z96f
  username: admin
  password: admin
  realm: safari

